[tasks.clippy]
command = "cargo"
# -D warnings treats all warnings as errors
args = ["clippy", "--", "-D", "warnings"]

# Release
[tasks.build-wasm-release]
dependencies = ["clippy"]
command = "cargo"
args = ["build", "--release", "--target", "wasm32-unknown-unknown"]

[tasks.wasm-release]
dependencies = ["build-wasm-release"]
command = "wasm-pack"
args = ["build", "--release", "--target", "web", "--out-dir", "web/src/pkg", "--no-pack"]

# Dev
[tasks.build-wasm]
dependencies = ["clippy"]
command = "cargo"
args = ["build", "--target", "wasm32-unknown-unknown"]

[tasks.wasm]
dependencies = ["build-wasm"]
command = "wasm-pack"
args = ["build", "--dev", "--target", "web", "--out-dir", "web/src/pkg", "--no-pack"]

[tasks.watch-wasm]
command = "cargo"
args = [
    "watch",
    "--ignore", "target/*",
    "--ignore", "web/*",
    "-x", "build --target wasm32-unknown-unknown",
    "-s", "wasm-pack build --dev --out-dir web/src/pkg --target web --no-pack",
]

[tasks.default]
dependencies = ["build-wasm"]
