[tasks.clippy]
command = "cargo"
# -D warnings treats all warnings as errors
args = ["clippy", "--", "-D", "warnings"]

[tasks.build]
dependencies = ["clippy"]
command = "cargo"
args = ["build"]

[tasks.build-wasm-release]
dependencies = ["clippy"]
command = "cargo"
args = ["build", "--release", "--target", "wasm32-unknown-unknown"]

[tasks.build-wasm]
dependencies = ["clippy"]
command = "cargo"
args = ["build", "--target", "wasm32-unknown-unknown"]

[tasks.wasm-release]
dependencies = ["build-wasm-release"]
command = "wasm-bindgen"
args = [
    "target/wasm32-unknown-unknown/release/wasm-test.wasm",
    "--out-dir", "web",
    "--target", "web"
]

[tasks.wasm]
dependencies = ["build-wasm"]
command = "wasm-bindgen"
args = ["target/wasm32-unknown-unknown/debug/wasm-test.wasm",
    "--out-dir", "web", "--target", "web"]

[tasks.watch-wasm]
command = "cargo"
args = [
    "watch",
    "--ignore", "target/*",
    "--ignore", "web/*",
    "-x", "build --target wasm32-unknown-unknown",
    "-s", "wasm-bindgen target/wasm32-unknown-unknown/debug/wasm-test.wasm --out-dir web --target web"
]

[tasks.run]
dependencies = ["clippy"]
command = "cargo"
args = ["run"]

[tasks.default]
dependencies = ["build"]
